### PR TITLE
Add talk for 04,2020

### PR DESCRIPTION
**Pull request by alenpokos**

### CODE REVIEW

**Comment by MarioBlazek** [comment]
Thank you for your talk proposal @alenpokos. Currently, all slots for April are full. Would you be kind to reconsider staging your talk some other month?

Here is a list of future [venues](https://github.com/zgphp/meetups#future-venues).

**Comment by MarioBlazek** [comment]
ping @alenpokos  :)

**Comment by alenpokos** [comment]
@MarioBlazek Sure, I will look for another month.

**Comment by MarioBlazek** [comment]
@alenpokos just realised that we have already agreed with Trikoder to host the meetup in October, would you reconsider to stage the talk then? If everything with COVID-19 calms down of course.

**Pull request closed without merging**
